from __future__ import annotations

import io
import shutil
import subprocess
import zipfile

import pytest

from app import jobs
from app.config import settings
from app.services import video as video_service

# The app decodes in-process via PyAV and needs no binary. These fixtures still
# shell out to the ffmpeg CLI to *synthesise* a test clip, which is a tooling
# dependency, not an application one - so this checks for the binary directly.
needs_ffmpeg = pytest.mark.skipif(
    shutil.which("ffmpeg") is None,
    reason="the ffmpeg CLI is needed to build test videos",
)

MISSING_JOB = "11111111-2222-3333-4444-555555555555"


@pytest.fixture
def sample_video(tmp_path):
    """A three second 320x180 test pattern, generated by FFmpeg."""
    path = tmp_path / "sample.mp4"
    subprocess.run(
        [
            "ffmpeg", "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "testsrc=size=320x180:rate=10:duration=3",
            "-pix_fmt", "yuv420p", str(path),
        ],
        check=True,
        timeout=60,
    )
    return path


def test_index_renders_the_upload_page(client):
    response = client.get("/")
    assert response.status_code == 200
    assert "Video to Image" in response.text
    assert "Drag &amp; drop a video here" in response.text
    assert str(settings.max_output_images) in response.text


def test_index_offers_the_new_options_and_notice(client):
    body = client.get("/").text
    assert "I just want a ZIP file" in body
    assert "Remember settings" in body
    assert "Please avoid directly linking to this file" in body
    assert "removed from our servers in 1 hour" in body
    assert "multiple IP addresses" in body


def test_index_offers_the_image_title_field(client):
    body = client.get("/").text
    assert 'id="title-input"' in body
    assert "Image title" in body
    assert "frame_00001.jpg" in body


@pytest.fixture
def processing_available(monkeypatch):
    """The URL form only renders where frames can actually be extracted, and
    this suite also runs on machines without FFmpeg."""
    from app.services import video as video_service

    monkeypatch.setattr(video_service, "ffmpeg_available", lambda: True)


def test_the_page_publishes_a_fetch_budget_for_the_browser(
    client, processing_available
):
    """A URL fetch can run for a minute, so the spinner needs a deadline."""
    from app.services import media_site as media_site_service

    body = client.get("/").text
    assert 'id="url-status"' in body

    expected = (
        settings.media_site_timeout_seconds
        if media_site_service.enabled()
        else settings.url_fetch_timeout_seconds
    ) + 15
    assert f'data-timeout-seconds="{expected}"' in body


def test_the_fetch_budget_shrinks_without_the_extractor(
    client, monkeypatch, processing_available
):
    monkeypatch.setattr(settings, "allow_media_site_urls", False)
    body = client.get("/").text
    expected = settings.url_fetch_timeout_seconds + 15
    assert f'data-timeout-seconds="{expected}"' in body


def test_every_step_including_the_loader_shows_its_place_in_the_flow(client):
    body = client.get("/").text
    for label in ("Step 1 of 3", "Step 2 of 3", "Step 3 of 3"):
        assert label in body
    # The loading card sits on the way to the results, so it carries step 3 too.
    loader = body.split('id="step-loading"')[1].split("</section>")[0]
    assert "Step 3 of 3" in loader
    assert "Extracting frames" in loader


def test_health_reports_status_and_features(client):
    payload = client.get("/health").json()
    assert payload["status"] == "ok"
    assert isinstance(payload["ffmpeg"], bool)
    # Lets a deployment be checked for whether it has the current build.
    assert payload["features"]["steps"] == 3
    assert payload["features"]["url_uploads"] is settings.allow_url_uploads
    assert payload["limits"]["max_output_images"] == settings.max_output_images


def test_upload_rejects_unsupported_extensions(client):
    response = client.post(
        "/api/upload", files={"file": ("notes.txt", io.BytesIO(b"hello"), "text/plain")}
    )
    assert response.status_code == 400
    assert "Unsupported file type" in response.json()["error"]


def test_upload_rejects_files_that_are_not_videos(client):
    response = client.post(
        "/api/upload",
        files={"file": ("clip.mp4", io.BytesIO(b"not a video" * 100), "video/mp4")},
    )
    assert response.status_code == 400
    assert "error" in response.json()
    assert list(settings.temp_dir.glob("*")) == []


def test_upload_enforces_the_size_limit(client, monkeypatch):
    monkeypatch.setattr(settings, "max_upload_size_mb", 1)
    payload = io.BytesIO(b"0" * (2 * 1024 * 1024))
    response = client.post(
        "/api/upload", files={"file": ("big.mp4", payload, "video/mp4")}
    )
    assert response.status_code == 400
    assert "larger than" in response.json()["error"]


def test_unknown_job_lookups_are_not_found(client):
    assert client.get(f"/api/result/{MISSING_JOB}").status_code == 404
    assert client.get(f"/api/download-all/{MISSING_JOB}").status_code == 404
    assert (
        client.post("/api/process", json={"job_id": MISSING_JOB}).status_code == 404
    )


def test_malformed_job_ids_are_not_found(client):
    assert client.get("/api/result/not-a-uuid").status_code == 404


def test_download_rejects_path_traversal(client):
    job_id, directory = jobs.create()
    jobs.write_meta(job_id, {"job_id": job_id, "images": []})
    (directory / "output" / "frame_00001.jpg").write_bytes(b"x")

    for attempt in ("..%2Fjob.json", "..", "%2Fetc%2Fpasswd"):
        assert client.get(f"/api/download/{job_id}/{attempt}").status_code == 404
    assert client.get(f"/api/download/{job_id}/frame_00001.jpg").status_code == 200


def test_invalid_process_payloads_are_rejected(client):
    response = client.post("/api/process", json={"method": "fps"})
    assert response.status_code == 422
    assert response.json()["error"]


def test_delete_job_is_idempotent_for_known_jobs(client):
    job_id, directory = jobs.create()
    assert client.delete(f"/api/job/{job_id}").json()["deleted"] is True
    assert not directory.exists()
    assert client.delete(f"/api/job/{job_id}").status_code == 404


@needs_ffmpeg
def test_uploaded_mp4_is_reported_as_mp4(client, tmp_path):
    """An .MP4 upload must not come back labelled MOV."""
    path = tmp_path / "GEMINI_GENERATED_VIDEO_18D1DA7B.MP4"
    subprocess.run(
        [
            "ffmpeg", "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "testsrc=size=320x180:rate=24:duration=2",
            "-pix_fmt", "yuv420p", "-c:v", "libx264", str(path),
        ],
        check=True,
        timeout=60,
    )
    with path.open("rb") as handle:
        body = client.post(
            "/api/upload", files={"file": (path.name, handle, "video/mp4")}
        ).json()
    assert body["video"]["format_name"] == "MP4"
    assert body["video"]["filename"] == path.name


@needs_ffmpeg
def test_quicktime_named_mp4_is_reported_as_mov(client, tmp_path):
    """The brand wins over a misleading extension."""
    real = tmp_path / "real.mov"
    subprocess.run(
        [
            "ffmpeg", "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "testsrc=size=320x180:rate=24:duration=2",
            "-pix_fmt", "yuv420p", "-c:v", "libx264", str(real),
        ],
        check=True,
        timeout=60,
    )
    disguised = tmp_path / "disguised.mp4"
    disguised.write_bytes(real.read_bytes())

    with disguised.open("rb") as handle:
        body = client.post(
            "/api/upload", files={"file": (disguised.name, handle, "video/mp4")}
        ).json()
    assert body["video"]["format_name"] == "MOV"


@needs_ffmpeg
def test_probe_reads_real_metadata(sample_video):
    info = video_service.probe(sample_video)
    assert (info.width, info.height) == (320, 180)
    assert info.duration == pytest.approx(3.0, abs=0.2)
    assert info.fps == pytest.approx(10.0, abs=0.1)


@needs_ffmpeg
def test_full_conversion_flow(client, sample_video):
    with sample_video.open("rb") as handle:
        upload = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        )
    assert upload.status_code == 200, upload.text
    job_id = upload.json()["job_id"]

    process = client.post(
        "/api/process",
        json={
            "job_id": job_id,
            "method": "count",
            "count": 4,
            "image_format": "jpg",
            "quality_preset": "high",
            "width": 160,
            "height": 90,
        },
    )
    assert process.status_code == 200, process.text
    result = process.json()
    assert result["count"] == 4
    assert result["options"]["format"] == "jpg"
    assert result["images"][0]["width"] == 160
    assert result["images"][0]["timestamp"] == 0.0

    reloaded = client.get(f"/api/result/{job_id}").json()
    assert reloaded["count"] == 4

    first = result["images"][0]
    image = client.get(first["url"])
    assert image.status_code == 200
    assert image.headers["content-type"] == "image/jpeg"
    assert client.get(first["thumbnail_url"]).status_code == 200

    bundle = client.get(result["download_all_url"])
    assert bundle.status_code == 200
    with zipfile.ZipFile(io.BytesIO(bundle.content)) as archive:
        assert len(archive.namelist()) == 4

    assert client.delete(f"/api/job/{job_id}").status_code == 200
    assert client.get(f"/api/result/{job_id}").status_code == 404


@needs_ffmpeg
def test_zip_only_skips_previews_and_prepares_the_archive(client, sample_video):
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    result = client.post(
        "/api/process",
        json={
            "job_id": job_id,
            "method": "count",
            "count": 5,
            "image_format": "jpg",
            "zip_only": True,
        },
    ).json()

    assert result["zip_only"] is True
    assert result["count"] == 5
    assert result["images"] == []          # nothing to display
    assert result["archive_size_bytes"] > 0  # archive built up front

    # No thumbnails were generated at all.
    assert list((settings.temp_dir / job_id / "thumbs").iterdir()) == []

    bundle = client.get(result["download_all_url"])
    assert bundle.status_code == 200
    with zipfile.ZipFile(io.BytesIO(bundle.content)) as archive:
        assert len(archive.namelist()) == 5


@needs_ffmpeg
def test_result_is_removed_after_too_many_download_addresses(client, sample_video):
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]
    client.post(
        "/api/process", json={"job_id": job_id, "method": "count", "count": 2}
    )

    url = f"/api/download-all/{job_id}"
    for index in range(settings.max_download_clients):
        response = client.get(url, headers={"x-forwarded-for": f"203.0.113.{index}"})
        assert response.status_code == 200

    blocked = client.get(url, headers={"x-forwarded-for": "203.0.113.99"})
    assert blocked.status_code == 404
    assert "too many different addresses" in blocked.json()["error"]
    assert client.get(f"/api/result/{job_id}").status_code == 404


@needs_ffmpeg
def test_repeat_downloads_from_one_address_are_unlimited(client, sample_video):
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]
    result = client.post(
        "/api/process", json={"job_id": job_id, "method": "count", "count": 2}
    ).json()

    for _ in range(6):
        assert client.get(result["images"][0]["url"]).status_code == 200
        assert client.get(result["download_all_url"]).status_code == 200


@needs_ffmpeg
def test_thumbnails_do_not_count_as_downloads(client, sample_video):
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]
    result = client.post(
        "/api/process", json={"job_id": job_id, "method": "count", "count": 2}
    ).json()

    for index in range(settings.max_download_clients + 3):
        response = client.get(
            result["images"][0]["thumbnail_url"],
            headers={"x-forwarded-for": f"198.51.100.{index}"},
        )
        assert response.status_code == 200
    assert client.get(f"/api/result/{job_id}").status_code == 200


@needs_ffmpeg
def test_output_limit_is_enforced_on_every_frame(client, sample_video, monkeypatch):
    monkeypatch.setattr(settings, "max_output_images", 5)
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    result = client.post(
        "/api/process",
        json={"job_id": job_id, "method": "every_frame", "image_format": "png"},
    ).json()
    assert result["count"] == 5
    assert result["truncated"] is True


@needs_ffmpeg
def test_output_budget_refuses_a_job_that_cannot_fit(client, sample_video, monkeypatch):
    monkeypatch.setattr(settings, "max_total_output_mb", 0)
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    response = client.post(
        "/api/process",
        json={"job_id": job_id, "method": "count", "count": 5, "image_format": "png"},
    )
    assert response.status_code == 400
    assert "Reduce the number of images" in response.json()["error"]
    # Nothing is left behind when the budget stops a job.
    assert list((settings.temp_dir / job_id / "output").iterdir()) == []


@needs_ffmpeg
def test_hopeless_batches_are_rejected_from_the_first_frame(
    client, sample_video, monkeypatch
):
    """A batch that cannot fit is refused immediately, not after minutes of work."""
    monkeypatch.setattr(settings, "max_total_output_mb", 1)
    monkeypatch.setattr(settings, "max_output_images", 500)
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    response = client.post(
        "/api/process",
        json={
            "job_id": job_id,
            "method": "count",
            "count": 500,
            "image_format": "png",
        },
    )
    assert response.status_code == 400
    error = response.json()["error"]
    assert "would produce roughly" in error
    assert "over the 1 MB limit" in error
    assert list((settings.temp_dir / job_id / "output").iterdir()) == []


@needs_ffmpeg
@pytest.mark.parametrize(
    ("payload", "label"),
    [
        ({"method": "interval", "interval": 30}, "interval longer than the video"),
        ({"method": "interval", "interval": 3}, "interval equal to the video"),
        ({"method": "count", "count": 1}, "a single image"),
        ({"method": "fps", "fps": 0.1}, "a frame rate below one per video"),
    ],
)
def test_single_frame_requests_return_one_image(client, sample_video, payload, label):
    """These used to fail with "no frames could be extracted"."""
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    response = client.post("/api/process", json={"job_id": job_id, **payload})
    assert response.status_code == 200, f"{label}: {response.text}"
    body = response.json()
    assert body["count"] == 1, label
    assert body["images"][0]["timestamp"] == 0.0


@needs_ffmpeg
def test_duration_limit_rejects_long_videos(client, sample_video, monkeypatch):
    monkeypatch.setattr(settings, "max_video_duration_seconds", 1)
    with sample_video.open("rb") as handle:
        response = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        )
    assert response.status_code == 400
    assert "longer than" in response.json()["error"]


@needs_ffmpeg
def test_image_title_names_the_files_and_the_archive(client, sample_video):
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    response = client.post(
        "/api/process",
        json={
            "job_id": job_id,
            "method": "count",
            "count": 2,
            "title": "Beach Sunset!",
        },
    )
    assert response.status_code == 200, response.text
    result = response.json()

    assert result["options"]["title"] == "Beach-Sunset"
    assert [item["filename"] for item in result["images"]] == [
        "Beach-Sunset_00001.jpg",
        "Beach-Sunset_00002.jpg",
    ]
    # The renamed files are still reachable through the download endpoint.
    assert client.get(result["images"][0]["url"]).status_code == 200
    assert client.get(result["images"][0]["thumbnail_url"]).status_code == 200

    bundle = client.get(result["download_all_url"])
    assert bundle.status_code == 200
    assert 'filename="Beach-Sunset.zip"' in bundle.headers["content-disposition"]
    with zipfile.ZipFile(io.BytesIO(bundle.content)) as archive:
        assert archive.namelist() == [
            "Beach-Sunset_00001.jpg",
            "Beach-Sunset_00002.jpg",
        ]


@needs_ffmpeg
def test_without_a_title_the_original_naming_is_kept(client, sample_video):
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    result = client.post(
        "/api/process", json={"job_id": job_id, "method": "count", "count": 1}
    ).json()

    assert result["options"]["title"] == ""
    assert result["images"][0]["filename"] == "frame_00001.jpg"

    bundle = client.get(result["download_all_url"])
    assert f'images-{job_id[:8]}.zip' in bundle.headers["content-disposition"]


@needs_ffmpeg
def test_a_hostile_title_cannot_escape_the_output_directory(client, sample_video):
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    result = client.post(
        "/api/process",
        json={
            "job_id": job_id,
            "method": "count",
            "count": 1,
            "title": "../../etc/passwd",
        },
    ).json()

    name = result["images"][0]["filename"]
    assert name == "etc-passwd_00001.jpg"
    assert jobs.SAFE_NAME_RE.match(name)
    assert client.get(result["images"][0]["url"]).status_code == 200
    # Everything stayed inside the job's own output directory.
    output = jobs.directory(job_id) / "output"
    assert [path.name for path in output.iterdir()] == [name]


@needs_ffmpeg
def test_odd_widths_are_packed_without_row_padding(client, sample_video):
    """libav aligns each row, so a 641px frame carries a 7696-byte stride for
    7684 bytes of pixels. Packing it wrongly shears the image diagonally."""
    with sample_video.open("rb") as handle:
        job_id = client.post(
            "/api/upload", files={"file": ("sample.mp4", handle, "video/mp4")}
        ).json()["job_id"]

    result = client.post(
        "/api/process",
        json={
            "job_id": job_id,
            "method": "count",
            "count": 2,
            "image_format": "png",
            "width": 641,
            "height": 361,
            "maintain_aspect": False,
        },
    ).json()

    assert result["images"][0]["width"] == 641
    assert result["images"][0]["height"] == 361

    from PIL import Image

    body = client.get(result["images"][0]["url"]).content
    with Image.open(io.BytesIO(body)) as image:
        assert image.size == (641, 361)
        # A stride bug shows up as the last column being padding, not picture.
        right_edge = image.convert("RGB").crop((640, 0, 641, 361)).getextrema()
        assert any(lo != 0 or hi != 0 for lo, hi in right_edge)


@needs_ffmpeg
def test_convert_returns_the_archive_in_one_request(client, sample_video):
    """No job is kept, so nothing can be lost between requests."""
    with sample_video.open("rb") as handle:
        response = client.post(
            "/api/convert",
            files={"file": ("sample.mp4", handle, "video/mp4")},
            data={
                "method": "count",
                "count": "3",
                "image_format": "jpg",
                "width": "320",
                "title": "One Shot",
            },
        )

    assert response.status_code == 200, response.text
    assert response.headers["content-type"] == "application/zip"
    assert 'filename="One-Shot.zip"' in response.headers["content-disposition"]
    with zipfile.ZipFile(io.BytesIO(response.content)) as archive:
        assert archive.namelist() == [
            "One-Shot_00001.jpg",
            "One-Shot_00002.jpg",
            "One-Shot_00003.jpg",
        ]


@needs_ffmpeg
def test_convert_leaves_nothing_on_disk(client, sample_video):
    before = sorted(p.name for p in jobs.root().iterdir())
    with sample_video.open("rb") as handle:
        assert (
            client.post(
                "/api/convert",
                files={"file": ("sample.mp4", handle, "video/mp4")},
                data={"method": "count", "count": "2"},
            ).status_code
            == 200
        )
    assert sorted(p.name for p in jobs.root().iterdir()) == before


@needs_ffmpeg
def test_convert_cleans_up_after_a_rejected_request(client, sample_video):
    before = sorted(p.name for p in jobs.root().iterdir())
    with sample_video.open("rb") as handle:
        response = client.post(
            "/api/convert",
            files={"file": ("sample.mp4", handle, "video/mp4")},
            data={"method": "fps", "fps": "0"},
        )
    assert response.status_code == 400
    assert "Frame rate" in response.json()["error"]
    assert sorted(p.name for p in jobs.root().iterdir()) == before


def test_convert_rejects_a_non_video_extension(client):
    response = client.post(
        "/api/convert",
        files={"file": ("notes.txt", io.BytesIO(b"nope"), "text/plain")},
        data={"method": "count", "count": "1"},
    )
    assert response.status_code == 400
    assert "Unsupported file type" in response.json()["error"]


@needs_ffmpeg
def test_convert_enforces_the_duration_limit(client, sample_video, monkeypatch):
    monkeypatch.setattr(settings, "max_video_duration_seconds", 1)
    with sample_video.open("rb") as handle:
        response = client.post(
            "/api/convert",
            files={"file": ("sample.mp4", handle, "video/mp4")},
            data={"method": "count", "count": "2"},
        )
    assert response.status_code == 400
    assert "longer than" in response.json()["error"]


def test_stateless_mode_is_advertised_to_the_page_and_health(client, monkeypatch):
    monkeypatch.setattr(settings, "stateless_conversion", True)
    assert client.get("/health").json()["features"]["stateless_conversion"] is True
    body = client.get("/").text
    assert 'data-stateless="true"' in body
    # ZIP-only is implied when there is nothing left to preview.
    assert "Generate &amp; download ZIP" in body


def test_the_retention_notice_matches_the_mode(client, monkeypatch):
    """In stateless mode nothing is stored, so promising an hour would lie."""
    stored = client.get("/").text
    assert "removed from our servers" in stored
    assert "Nothing was kept on the server" not in stored

    monkeypatch.setattr(settings, "stateless_conversion", True)
    stateless = client.get("/").text
    assert "Nothing was kept on the server" in stateless
    assert "removed from our servers" not in stateless
